name: app1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  connectivity_plus: ^5.0.2
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  font_awesome_flutter: ^10.4.0
  gap: ^3.0.1
  get_it: ^7.6.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  outlined_text: ^1.0.1
  popover: ^0.2.8+2
  readmore: ^2.2.0
  smooth_page_indicator: ^1.1.0
  stream_transform: ^2.1.0
  stroke_text: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
