name: app1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  country_code_picker: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^7.1.1
  http: ^0.13.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
