// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDok4ncNpCSS25ZAA3YjHdB3TFu8pzGy9A',
    appId: '1:115730735502:web:89a278405fd7aa5438c4df',
    messagingSenderId: '115730735502',
    projectId: 'deliverease-4c543',
    authDomain: 'deliverease-4c543.firebaseapp.com',
    storageBucket: 'deliverease-4c543.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMUCLw7PxZibsrUSvqjEPTheQ799IGLw',
    appId: '1:115730735502:android:0804e848bf2bcc5b38c4df',
    messagingSenderId: '115730735502',
    projectId: 'deliverease-4c543',
    storageBucket: 'deliverease-4c543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNdf_DH9owoXrLugf_cjD9RObNVGHTlUM',
    appId: '1:115730735502:ios:ee26e1afebbae20c38c4df',
    messagingSenderId: '115730735502',
    projectId: 'deliverease-4c543',
    storageBucket: 'deliverease-4c543.appspot.com',
    iosClientId: '115730735502-lbptf980pogd3f0mkph2mr5r7iidhqt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.akshit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNdf_DH9owoXrLugf_cjD9RObNVGHTlUM',
    appId: '1:115730735502:ios:ee26e1afebbae20c38c4df',
    messagingSenderId: '115730735502',
    projectId: 'deliverease-4c543',
    storageBucket: 'deliverease-4c543.appspot.com',
    iosClientId: '115730735502-lbptf980pogd3f0mkph2mr5r7iidhqt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.akshit',
  );
}
