// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh03xYqbx31yBbgeMQAcBb4cVQn7QDL8Y',
    appId: '1:378216902175:web:0f041dc497df3db72faf2a',
    messagingSenderId: '378216902175',
    projectId: 'app1-900e8',
    authDomain: 'app1-900e8.firebaseapp.com',
    storageBucket: 'app1-900e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvvHbZF9qoyBwjijxbSE5ZX2HDZSUByhQ',
    appId: '1:378216902175:android:9439bc13f20e1e0c2faf2a',
    messagingSenderId: '378216902175',
    projectId: 'app1-900e8',
    storageBucket: 'app1-900e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVRoCopM_KfPUegQyi7k--yblzTqh6Ec',
    appId: '1:378216902175:ios:3bd2ce2a7affbbc02faf2a',
    messagingSenderId: '378216902175',
    projectId: 'app1-900e8',
    storageBucket: 'app1-900e8.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVRoCopM_KfPUegQyi7k--yblzTqh6Ec',
    appId: '1:378216902175:ios:3bd2ce2a7affbbc02faf2a',
    messagingSenderId: '378216902175',
    projectId: 'app1-900e8',
    storageBucket: 'app1-900e8.appspot.com',
    iosBundleId: 'com.example.app1',
  );
}
